ErgoSalud/Controllers/EncuestasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using ErgoSalud.Models;
//using IronPdf;
//using iTextSharp.text.pdf;
//using PdfSharp.Drawing;
//using Rotativa;
using System.Diagnostics;
using PdfSharp;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;
using IronPdf;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Collections;
using iTextSharp.text.html.simpleparser;
using iTextSharp.tool.xml;
using iTextSharp.tool.xml.css;
using iTextSharp.tool.xml.pipeline.css;

namespace ErgoSalud.Controllers
{
    [Authorize]

    public class EncuestasController : Controller
    {
        private CastSoft_LETConsultingEntities db = new CastSoft_LETConsultingEntities();

        // GET: Encuestas
        public ActionResult Index()
        {
            //List<ERGOS_Empresas_N01> Folios = db.ERGOS_Empresas_N01.ToList();
            ViewBag.ERGOS_Empresas_N01List = new SelectList(db.ERGOS_Empresas_N01.Where(E => E.deleted_at == null), "id_empresa", "Razon_Social");

            // var eRGOS_Cuestionarios_Trabajador_N01 = db.ERGOS_Cuestionarios_Trabajador_N01.Include(e => e.ERGOS_Cuestionarios_N01).Include(e => e.ERGOS_Empresas_N01);
            return View(db.ERGOS_Cuestionarios_Trabajador_N01.Include(c => c.ERGOS_Cuestionarios_N01).Include(e => e.ERGOS_Empresas_N01).Where(e => e.ERGOS_Empresas_N01.deleted_at == null).ToList());
        }

        public ActionResult Reporte_PDF(int id_CT, int id_C)
        {
            var uri = new Uri("http://localhost:52643/Reportes/AOwYbqttJ6fobQAreA9mBUt4dmB5CBtuirmBaf4AhwNvjDfuIhma4ZpjMxmTosLw?id_CT=" + id_CT + "&id_C=" + id_C);
            var urlToPdf = new HtmlToPdf
            {
                LoginCredentials = new HttpLoginCredentials()
                {
                    NetworkUsername = "KEVIN@gmail.com",
                    NetworkPassword = "Pa$$w0rd2"
                }
            };

            //var pdf = urlToPdf.RenderUrlAsPdf(uri);
            string download = new WebClient().DownloadString(uri);

            string css = @"@import url('chrome://resources/css/roboto.css'); html { direction: ltr; }
            body { font - family: Roboto, 'Segoe UI', Tahoma, sans - serif; font - size: 81.25 %; }
            button { font - family: Roboto, 'Segoe UI', Tahoma, sans - serif; }
            html { touch - action: pan - x pan - y; }
            body { background - color: rgb(82, 86, 89); color: v…ry - text - color); line - height: 154 %; margin: 0px; }
            viewer - page - indicator { visibility: hidden; z - index: 2; }
            viewer - pdf - toolbar { position: fixed; width: 100 %; z - index: 4; }
            #content { height: 100%; position: fixed; width: 100%; z-index: 1; } viewer-ink-host, #plugin { height: 100%; position: absolute; width: 100%; } #sizer { position: absolute; z-index: 0; } @media (max-height: 250px) {↵  viewer-pdf-toolbar { display: none; }}@media (max-height: 200px) { viewer-zoom-toolbar { display: none; }}@media (max-width: 300px) {viewer-zoom-toolbar { display: none; }↵}", "html { --google-red-100-rgb: 244, 199, 195; --goog…ndary-opacity: 0.7; --light-primary-opacity: 1; } html { --google-blue-50-rgb: 232, 240, 254; --goog…90); --cr-toggle-color: var(--google-blue-500); }", "html[dark] { --cr-primary-text-color: var(--google…title-text-color: var(--cr-primary-text-color); }", "html { --cr-actionable_-_cursor: pointer; --cr-but…t); --cr-form-field-label_-_margin-bottom: 8px; }", "[hidden] { display: none !important; }", "html { --layout_-_display: flex; --layout-inline_-…out-invisible_-_visibility: hidden  !important; }", "html { --shadow-transition_-_transition: box-shado… 0, 0.12), 0 11px 15px -7px rgba(0, 0, 0, 0.4); }", "html { --iron-icon-height: 20px; --iron-icon-width…x; --viewer-icon-ink-color: rgb(189, 189, 189); }"";

            byte[] bytes;
            using (var ms = new MemoryStream())
            {
                using (var doc = new Document())
                {
                    using (var writter = PdfWriter.GetInstance(doc, ms))
                    {
                        doc.Open();
                        using (var htmlWorker = new HTMLWorker(doc))
                        {
                            using (var sr = new StringReader(download))
                            {
                                //htmlWorker.Parse(sr);
                                XMLWorkerHelper.GetInstance().ParseXHtml(writter, doc, sr);
                            }
                        }
                        using (var srHtml = new StringReader(download))
                        {
                            XMLWorkerHelper.GetInstance().ParseXHtml(writter, doc, srHtml);
                        }
                        using (var msCss = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(css)) )
                        {
                            using (var msHtml = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(download)))
                            {

                                XMLWorkerHelper.GetInstance().ParseXHtml(writter, doc, msHtml, msCss);
                            }
                        }
                        doc.Close();
                    }
                }
                bytes = ms.ToArray();
                return File(bytes, "application/pdf");
            }


                // MemoryStream ms = new MemoryStream();

                //return new ActionAsPdf("AOwYbqttJ6fobQAreA9mBUt4dmB5CBtuirmBaf4AhwNvjDfuIhma4ZpjMxmTosLw", new { id_CT = Request.Params["id_CT"] });
                //return File(document.BinaryData, "application/pdf;");/
         //       return View();
        }
        public ActionResult Reporte_General_PDF(int id)
        {
            var uri = new Uri("http://localhost:52643/Reportes/ReGOwYbqttJ6fobQArasdsdsdHIhihisdih876AhwNvjDfGFasauIhma4ZpjMxmTosLw?id=" + id);
            //var uri = new Uri("http://letconsultingpartner.castsoft.live/Reportes/ReGOwYbqttJ6fobQArasdsdsdHIhihisdih876AhwNvjDfGFasauIhma4ZpjMxmTosLw?id=" + id);
            var urlToPdf = new HtmlToPdf
            {
                LoginCredentials = new HttpLoginCredentials()
                {
                    NetworkUsername = "akshaybhagwat76@gmail.com",
                    NetworkPassword = "Pa$$w0rd2"
                }
            };

            var pdf = urlToPdf.RenderUrlAsPdf(uri);
            //pdf.SaveAs(Path.Combine(Directory.GetCurrentDirectory(), "UrlToPdfExample2.Pdf"));


            //IronPdf.HtmlToPdf Renderer = new IronPdf.HtmlToPdf();
            //// Render an HTML document or snippet as a string
            //PdfDocument PDF = Renderer.RenderHtmlAsPdf("<h1>Hello World</h1>");
            ////PdfDocument PDF2 = Renderer.RenderUrlAsPdf("http://localhost:52643/Reportes/ReGOwYbqttJ6fobQArasdsdsdHIhihisdih876AhwNvjDfGFasauIhma4ZpjMxmTosLw?id="+ id);
            //PdfDocument PDF2 = Renderer.RenderUrlAsPdf("http://letconsultingpartner.castsoft.live/Reportes/ReGOwYbqttJ6fobQArasdsdsdHIhihisdih876AhwNvjDfGFasauIhma4ZpjMxmTosLw?id=" + id);


            MemoryStream ms = new MemoryStream();


            return File(pdf.BinaryData, "application/pdf;");
            //return View();

        }



        public ActionResult Glabal_Results()
        {
            return View();
        }
        public JsonResult Get_Centros_Trabajo(int id_empresa)
        {

            //int id = Int32.Parse(id_categoria);
            object dato = null;
            try
            {

                var productos_gotten = (from Centros in db.ERGOS_Centros_Trabajo_N01
                                        join Empresas in db.ERGOS_Empresas_N01 on Centros.id_empresa equals Empresas.id_empresa
                                        where Empresas.id_empresa == id_empresa
                                        select new { Centros.Nombre_centro_trabajo, Centros.id_centro_trabajo });

                dato = productos_gotten.ToArray();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(dato, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Get_departamentos(int id_centro_trabajo)
        {

            //int id = Int32.Parse(id_categoria);
            object dato = null;
            try
            {

                var productos_gotten = (from Deptos in db.ERGOS_Departamentos_N01
                                        where Deptos.id_centro_trabajo == id_centro_trabajo
                                        select new { Deptos.id_departamento, Deptos.Departamento });

                dato = productos_gotten.ToArray();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(dato, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Search_Empresas(int ERGOS_Empresas_N01List)
        {


            var eRGOS_Cuestionarios_Trabajador_N01 = db.ERGOS_Cuestionarios_Trabajador_N01.Include(e => e.ERGOS_Cuestionarios_N01).Include(e => e.ERGOS_Empresas_N01).Where(e => e.id_empresa == ERGOS_Empresas_N01List);
            return View(eRGOS_Cuestionarios_Trabajador_N01.ToList());
        }


        public ActionResult Resultados(int id)
        {
            try
            {
                ViewBag.Categorias = (from total in db.fnDemo_N035_Categorias_Pilot(id)
                                      select new Respuestas
                                      {
                                          Canalizado = total.Canalizado,
                                          Dominio_1 = total.Dom_1,
                                          Dominio_2 = total.Dom_2,
                                          Dominio_3 = total.Dom_3,
                                          Dominio_4 = total.Dom_4,

ErgoSalud/Views/Encuestas/Delete.cshtml
@model ErgoSalud.Models.ERGOS_Cuestionarios_Trabajador_N01

@{
    ViewBag.Title = "Delete";
}

<hr />
<h2>Confirmación de Eliminación</h2>
<h4 style="color:red">¿Realmente quiere Eliminar la Encuesta No. <span style="color:black">@Html.DisplayFor(model => model.id_trabajador)</span>?</h4>
<div>



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <br><br>
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" />
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
        </div><br>
    }
</div>

ErgoSalud/Views/Encuestas/Details.cshtml
@model ErgoSalud.Models.ERGOS_Cuestionarios_Trabajador_N01

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ERGOS_Cuestionarios_Trabajador_N01</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id_trabajador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_trabajador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado_Civil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado_Civil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nivel_Esudios)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nivel_Esudios)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ocupacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ocupacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_puesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_puesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_Contratacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_Contratacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_Jornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_Jornada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rotacion_Turno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rotacion_Turno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experiencia_puesto_actual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experiencia_puesto_actual)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experiencia_puesto_laboral)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experiencia_puesto_laboral)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ERGOS_Cuestionarios_N01.Cuestionario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ERGOS_Cuestionarios_N01.Cuestionario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ERGOS_Empresas_N01.Razon_Social)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ERGOS_Empresas_N01.Razon_Social)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_cuestionario_trabajador }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ErgoSalud/Views/Encuestas/Glabal_Results.cshtml
<div class="raw">
    <h1>Resultados Globales </h1>
</div>

ErgoSalud/Views/Encuestas/Index.cshtml
@model IEnumerable<ErgoSalud.Models.ERGOS_Cuestionarios_Trabajador_N01>

@{
    ViewBag.Title = "Index";
}

<script>
    function show_modal(id_CT, id_C) {
        //Swal.fire({
        //    title: "<i>Title</i>",
        //    html: "Testno  sporocilo za objekt: <b>test</b>",
        //    confirmButtonText: "V <u>redu</u>",
        //});
        alert(id_CT);
        alert(id_C);

        var firstname = "abc";
        var username = "abcd";


        $("#myModal").modal()
        
    }
    
    </script>
<h2>Números de Folio</h2>
<div class="row">

    @Html.ActionLink("Nuevo Folio", "Create", null, new { @class = "btn btn-success", @style = "float:left;margin-left:15px" })

    @using (Html.BeginForm("Search_Empresas", "Encuestas", FormMethod.Get))
    {

        @Html.DropDownList("ERGOS_Empresas_N01List", null, new { @class = "form-control", @style = "float:left;margin-left:5px" })
        <input type="submit" class="btn btn-primary" value="Buscar" style="float:left;margin-left:5px">
    }
    <br>
</div>
<br>
<div class="table-responsive">

    <table class="table table-hover table-condensed">
        <tr>
            <th>
                @Html.DisplayName("No. Folio")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fecha)
            </th>
            <th>
                @Html.DisplayName("Ocupación")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ERGOS_Cuestionarios_N01.Cuestionario)
            </th>
            <th>
                @Html.DisplayName("Empresa")
            </th>
            <th>Acción</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id_trabajador)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ocupacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ERGOS_Departamentos_N01.Departamento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ERGOS_Cuestionarios_N01.Cuestionario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ERGOS_Empresas_N01.Razon_Social)
                </td>
                <td>
                    <a title="Editar" href="@Url.Action("Edit", new { id = item.id_cuestionario_trabajador })">
                        <i class="fa fa-edit" title="Editar" style="font-size:23px"></i>
                    </a>
                    @*data-toggle="modal" data-target="#GSCCModal"*@
                    @*href="@Url.Action("Encuesta", "Trabajador_Resultados", new { id_CT = item.id_cuestionario_trabajador, id_C = item.ERGOS_Cuestionarios_N01.id_cuestionario })"*@
                    <a href="#" data-toggle="modal" data-target="#@item.id_cuestionario_trabajador">
                        <i class="fa fa-file-text" title="Encuesta" style="font-size:20px;" aria-hidden="true"></i>
                    </a>
                    <a href="@Url.Action("Delete", new { id=item.id_cuestionario_trabajador })">
                        <i class="fa fa-trash-o" title="Eliminar" style="font-size:23px"></i>
                    </a>
                    <a href="@Url.Action("Resultados", new { id=item.id_cuestionario_trabajador })">
                        <i class="fa fa-check-circle" aria-hidden="true" style="color:green;font-size:23px" title="Resultados"></i>
                    </a>
                    <a href="@Url.Action("Reporte_PDF", "Encuestas", new {id_CT = item.id_cuestionario_trabajador ,id_C=item.id_encuesta })"><i class="fa fa-file-pdf-o" title="Encuesta Digital" style="font-size:20px;color:red" aria-hidden="true"></i> </a>

                </td>
            </tr>

            <div id="@item.id_cuestionario_trabajador" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;  </button>
                            <h4 class="modal-title" id="myModalLabel">Previa a Encuesta</h4>
                        </div>
                        <div class="modal-body" align="justify">
                            <p>
                                <h4>Para la aplicación del cuestionario deberán cumplirse, al menos, las condiciones siguientes:</h4>

                                <b> 1.</b>	Explicar el objetivo de la evaluación;    <br>   <br>
                                El objetivo es: Establecer los elementos para identificar, analizar y prevenir los factores de riesgo psicosocial, así como para promover un entorno organizacional favorable en los centros de trabajo.<br><br>

                                Oblicaciones de los trabajadores: <br> <br>
                                <b>6.1</b> Observar las medidas de prevención y, en su caso, de control que dispone esta Norma, así como las que establezca el patrón para: controlar los factores de riesgo psicosocial, colaborar para contar con un entorno organizacional favorable y prevenir actos de violencia laboral.
                                <br><b> 6.2</b> Abstenerse de realizar prácticas contrarias al entorno organizacional favorable y actos de violencia laboral.
                                <br><b> 6.3</b> Participar en la identificación de los factores de riesgo psicosocial y, en su caso, en la evaluación del entorno organizacional.
                                <br><b> 6.4</b> Informar sobre prácticas opuestas al entorno organizacional favorable y denunciar actos de violencia laboral, utilizando los mecanismos que establezca el patrón para tal efecto y/o a través de la comisión de seguridad e higiene, a que se refiere la NOM-019-STPS-2011, o las que la sustituyan.
                                <br><b>6.5</b> Informar por escrito al patrón directamente, a través de los servicios preventivos de seguridad y salud en el trabajo o de la comisión de seguridad e higiene; haber presenciado o sufrido un acontecimiento traumático severo. El escrito deberá contener al menos: la fecha de elaboración; el nombre del trabajador que elabora el escrito; en su caso, el nombre de los trabajadores involucrados; la fecha de ocurrencia, y la descripción del(los) acontecimiento(s).
                                <br><b>6.6</b> Participar en los eventos de información que proporcione el patrón.
                                <br><b>6.7</b> Someterse a los exámenes médicos y evaluaciones psicológicas que determinan la presente Norma y/o las normas oficiales mexicanas que al respecto emitan la Secretaría de Salud y/o la Secretaría del Trabajo y Previsión Social, y a falta de éstas, los que indique la institución de seguridad social o privada, o el médico o psicólogo o psiquiatra del centro de trabajo o de la empresa.

                            </p>
                        </div>
                        <div class="modal-footer">
                            <a href="@Url.Action("Encuesta", "Trabajador_Resultados", new { id_CT = item.id_cuestionario_trabajador, id_C = item.ERGOS_Cuestionarios_N01.id_cuestionario })" class="btn btn-primary">Continuar</a>
                        </div>
                    </div>
                </div>
            </div>

        }

    </table>
</div>

ErgoSalud/Views/Encuestas/Index2.cshtml
@model IEnumerable<ErgoSalud.Models.ERGOS_Cuestionarios_Trabajador_N01>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id_trabajador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado_Civil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nivel_Esudios)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ocupacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Departamento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tipo_puesto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tipo_Contratacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tipo_Jornada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rotacion_Turno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Experiencia_puesto_actual)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Experiencia_puesto_laboral)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ERGOS_Cuestionarios_N01.Cuestionario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ERGOS_Empresas_N01.Razon_Social)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.id_trabajador)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Edad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado_Civil)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nivel_Esudios)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ocupacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Departamento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tipo_puesto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tipo_Contratacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tipo_Jornada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rotacion_Turno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Experiencia_puesto_actual)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Experiencia_puesto_laboral)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ERGOS_Cuestionarios_N01.Cuestionario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ERGOS_Empresas_N01.Razon_Social)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_cuestionario_trabajador }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_cuestionario_trabajador }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_cuestionario_trabajador })
        </td>
    </tr>
}

</table>